-- MySQL Script generated by MySQL Workbench
-- Wed Feb 19 19:53:54 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

CREATE DATABASE endamoStore;

-- -----------------------------------------------------
-- Table `endamo`.`Direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Direccion (
  `idDireccion` INT NOT NULL AUTO_INCREMENT,
  `avenida` VARCHAR(45) NULL,
  `zona` VARCHAR(45) NULL,
  `numero_casa` VARCHAR(45) NULL,
  PRIMARY KEY (`idDireccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `endamo`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Empresa (
  `idEmpresa` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `propietario` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`idEmpresa`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `endamo`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Usuario (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `fecha_nacimiento` VARCHAR(45) NULL,
  `fecha_registro` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `Direccion_idDireccion` INT NOT NULL,
  `avatar` VARCHAR(45) NULL,
  `Empresa_idEmpresa` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  CONSTRAINT `fk_Usuario_Direccion`
    FOREIGN KEY (`Direccion_idDireccion`)
    REFERENCES Direccion (`idDireccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Empresa1`
    FOREIGN KEY (`Empresa_idEmpresa`)
    REFERENCES Empresa (`idEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `endamo`.`Entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Entrega (
  `idEntrega` INT NOT NULL AUTO_INCREMENT,
  `entregado` TINYINT NULL,
  PRIMARY KEY (`idEntrega`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `endamo`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Factura (
  `idFactura` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `idUsuario` VARCHAR(45) NULL,
  `Entrega_idEntrega` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idFactura`),
  CONSTRAINT `fk_Factura_Entrega1`
    FOREIGN KEY (`Entrega_idEntrega`)
    REFERENCES Entrega (`idEntrega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES Usuario (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `endamo`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Producto (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `precio` DECIMAL(2) NULL,
  `cantidad` INT NULL,
  `Empresa_idEmpresa` INT NOT NULL,
  PRIMARY KEY (`idProducto`),
  CONSTRAINT `fk_Producto_Empresa1`
    FOREIGN KEY (`Empresa_idEmpresa`)
    REFERENCES Empresa (`idEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `endamo`.`Detalle_factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Detalle_factura (
  `cantidad` INT NULL,
  `precio` DECIMAL(2) NULL,
  `Factura_idFactura` INT NOT NULL,
  `Producto_idProducto` INT NOT NULL,
  CONSTRAINT `fk_Detalle_factura_Factura1`
    FOREIGN KEY (`Factura_idFactura`)
    REFERENCES `Factura` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detalle_factura_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES Producto (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `endamo`.`Tipo_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Tipo_Usuario (
  `idTipo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idTipo`),
  CONSTRAINT `fk_Tipo_Usuario_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES Usuario (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `endamo`.`Deseo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Deseo (
  `idUsuario` INT NOT NULL,
  `idProducto` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Producto_idProducto` INT NOT NULL,
  PRIMARY KEY (`idUsuario`, `idProducto`),
  CONSTRAINT `fk_Deseo_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES Usuario (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Deseo_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES Producto (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `endamo`.`Tarjeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Tarjeta (
  `idTarjeta` INT NOT NULL AUTO_INCREMENT,
  `numero_tarjeta` INT NULL,
  `clave` INT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idTarjeta`),
  CONSTRAINT `fk_Tarjeta_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES Usuario (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


